name: kernel-kit
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends curl wget ca-certificates git file squashfs-tools xz-utils diffutils patch make flex bison python3 bc bzip2 kmod rsync libelf-dev libssl-dev dwarves gcc gcc-multilib jq
          curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o /usr/local/bin/vercmp -
          echo "dash dash/sh boolean false" | debconf-set-selections
          DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
      - name: Build kernel
        run: |
          cd kernel-kit
          cp -f 6.1.x-x86_64-build.conf build.conf
          CREATE_KBUILD_SFS=yes ./build.sh
          mkdir small-output
          mv `ls output/kernel_sources-*.sfs* output/kbuild-*.sfs* output/*.tar* 2>/dev/null` small-output
      - name: Upload kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel-kit-output-6.1.x-x86_64
          path: kernel-kit/small-output
          retention-days: 16
